module.exports = {
  types: [
    { value: 'feat', name: 'feat:     ✨  新功能' },
    { value: 'fix', name: 'fix:      🐛  修复 BUG' },
    { value: 'docs', name: 'docs:     📝  修改文档' },
    { value: 'style', name: 'style:    💄  代码格式修改 (不影响逻辑)' },
    { value: 'refactor', name: 'refactor: ♻️   代码重构 (非修复或新功能)' },
    { value: 'perf', name: 'perf:     ⚡️  性能优化' },
    { value: 'test', name: 'test:     ✅  测试用例修改' },
    { value: 'build', name: 'build:    📦  构建流程、外部依赖变更 (如升级 npm 包)' },
    { value: 'ci', name: 'ci:       🎡  CI 配置变更' },
    { value: 'chore', name: 'chore:    🔨  日常事务、辅助工具变更' },
    { value: 'revert', name: 'revert:   ⏪  代码回滚' },
  ],
  scopes: [
    { name: 'hooks' },
    { name: 'components' },
    { name: 'utils' },
    { name: 'locale' },
    { name: 'dependencies' },
    { name: 'configs' },
    { name: 'docs' },
    { name: 'release' },
  ],
  allowCustomScopes: true,
  allowBreakingChanges: ['feat', 'fix'],
  messages: {
    type: '选择要提交的更改类型:',
    scope: '选择更改影响的范围 (可选):',
    customScope: '请输入自定义的更改范围:',
    subject: '写一个简短的描述 (建议不超过 72 个字符):\n',
    body: '详细描述更改原因 (可选). 使用 "|" 换行:\n',
    breaking: '列出破坏性更新 BREAKING CHANGES (可选):\n',
    footer: '列出关闭的 ISSUES (可选). 如: #31, #34:\n',
    confirmCommit: '确定提交上面的更改?',
  },
  footerPrefix: 'close',
  subjectLimit: 72,
};
